name: deployment

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      build_version:
        required: true
        type: string
      actor:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Display Environment Info
        run: echo "Deploying to ${{ github.environment }} environment..."

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Update Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ghcr.io/${{ inputs.actor }}/learning-github-container-registry-api:${{ inputs.build_version }} \
            --set registries="ghcr.io=${{ secrets.GHCR_USERNAME }}=${{ secrets.TOKEN }}"

